# wangbin's test acocunt
# TWILIO_ACCOUNT_SID: AC9d529dcb2318419fd2e9bd968b228811
# TWILIO_AUTH_TOKEN: ca360c559d117d2257886ff41165e458
# TWILIO_PHONE_NUMBER: '+85258086771'
# TWILIO_PHONE_PREFIX: '+86'

# # zoom test account
# TWILIO_ACCOUNT_SID: ACa0199e9398ed47b98fc32ab83116ca6a
# TWILIO_AUTH_TOKEN: e54d3773ac79339c6ad0cb31b602bdeb
# TWILIO_PHONE_NUMBER: '+18182178338'
# TWILIO_PHONE_PREFIX: '+86'

# # zoom live account
TWILIO_ACCOUNT_SID: AC271a22360bafc0680e162c0c4a9f44a6
TWILIO_AUTH_TOKEN: ce0b2ee5e86187e58f2ef967a201f610
TWILIO_PHONE_NUMBER: '+1 844-733-8331'
TWILIO_PHONE_PREFIX: '+1'


# notification types
notify_message: 0
notify_user: 1
notify_finance: 2
notify_errand: 3
