# wangbin's test acocunt
# TWILIO_ACCOUNT_SID: AC9d529dcb2318419fd2e9bd968b228811
# TWILIO_AUTH_TOKEN: ca360c559d117d2257886ff41165e458
# TWILIO_PHONE_NUMBER: '+85258086771'
# TWILIO_PHONE_PREFIX: '+86'

# # zoom test account
# TWILIO_ACCOUNT_SID: ACa0199e9398ed47b98fc32ab83116ca6a
# TWILIO_AUTH_TOKEN: e54d3773ac79339c6ad0cb31b602bdeb
# TWILIO_PHONE_NUMBER: '+18182178338'
# TWILIO_PHONE_PREFIX: '+86'

# notification types
notify_message: 0
notify_user: 1
notify_finance: 2
notify_errand: 3

GOOGLE_MAP_KEY: AIzaSyCg1msbF4Lq_1PIDsHcqUD6GrsiPJ5fbvg
