host_url: http://localhost:3000
angular_url: http://localhost:3012

facebook:
  key: 1724095974486718
  secret: 0313f4e1a4cb8e894a741f2f888d0be2

google:
  key: 958055516479-8gttm4lgu9rmfv85ksku23ime1268rk7.apps.googleusercontent.com
  secret: 8-cJsnBVAg9n0Yzusl_ZqiXv

stripe_publish_key: pk_test_YH06zNfVEQqzGET9dTJaAWcZ
stripe_secret_key: sk_test_HfZ1fWSjJbhVOJxxajBnbgwI 
