host_url: http://localhost:3000
angular_url: http://localhost:3012

facebook:
  key: 1724095974486718
  secret: 0313f4e1a4cb8e894a741f2f888d0be2

google:
  key: 474946006162-uajhr7fbm4rh6puv8o0kgeqeq1h9a9vk.apps.googleusercontent.com
  secret: P8qiKdia5j2iPZb6k_dErWSK

stripe_publish_key: pk_test_9MLCt7tfGDELF03VZN7u4b7h 
stripe_secret_key: sk_test_SoecKP7tInvHVFjxlu0egAFH
